### ISSUE TITLE
Campo  customizado para inserir antes do link de pagamento

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/woocommerce-invoice-payment#32]
Dentro de configurações do plugin ter uma opção de alterar o texto que sera inserido antes do link de pagamento:

![image](https://github.com/LinkNacional/woocommerce-invoice-payment/assets/636225/4e05428d-ec4f-49a6-94c1-3c714745f1a8)

**Comment by brunoferreiralkn** [comment]
Das configurações do plugin ou nas configurações dentro da fatura?
