### ISSUE TITLE
O plugin está fora das normativas do WordPress, não se pode usar curl nem se pode usar echo sem escapar o atributo

### ISSUE THREAD

**Issue by brunoferreiralkn** [LinkNacional/woocommerce-invoice-payment#37]
@brunoferreiralkn Atenção, o plugin está fora das normativas do WordPress, não se pode usar curl nem se pode usar echo sem escapar o atributo:

- [ ] Necessário substituir echo por esc_attr_e ou esc_html_e dependendo do contexto;
- [ ] Necessário substituir curl por wp_remote_request

**Não** podemos nos desviar das normativas do WordPress pois nosso plugin pode ser reprovado e excluído da loja caso não sigamos a risca as normativas! Issue aberta, caso haja dúvidas pode me chamar. Issue aberta #36

_Originally posted by @emanuellopess in https://github.com/LinkNacional/woocommerce-invoice-payment/issues/35#issuecomment-1789730416_

**Comment by GuilhermeLinkNacional** [comment]
Resolvido na #36
