### ISSUE TITLE
Configuração para evitar inserção de email

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/woocommerce-invoice-payment#42]
Habilitar nas configurações de habilitar ou desabilitar do plugin recurso de não ser obrigatório a inserção do email para abertura da invoice.

Atualmente adicionamos este tipo de recurso via plugin trecho de código:

`add_filter( 'woocommerce_order_email_verification_required', function ( $email_verification_required, $order, $context ){
	return false;
}, 10, 3 );`

**Comment by emanuellopess** [comment]
Adicionar configuração que vem habilitada por padrão na área de configurações do plugin
