### ISSUE TITLE
Listagem de moeda nas configurações da fatura

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/woocommerce-invoice-payment#49]
Ao adicionar uma fatura o campo MOEDA, precisa ser alterado para ordem alfabética e seguir a regra: sigla moeda - nome pais, exemplo:

USD - Dólar Estados unidenses

Abaixo segue foto do local como esta atualmente e precisa alterar.
![image](https://github.com/LinkNacional/woocommerce-invoice-payment/assets/636225/843b6bc5-cfec-4354-94c6-aea62993baed)

**Comment by helonfranca02** [comment]
Concluído!
