### ISSUE TITLE
Bug ao clicar na seção de editar faturas

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/woocommerce-invoice-payment#66]
Ao clicar na seção dentro da barra lateral "editar faturas" é disparado um erro crítico, necessita correção

![image](https://github.com/LinkNacional/woocommerce-invoice-payment/assets/74307223/da0d002a-facf-4944-b204-f5161badb57d)
![image](https://github.com/LinkNacional/woocommerce-invoice-payment/assets/74307223/cc77ee9a-f10c-4d17-a541-40eb9204be0e)

**Comment by helonfranca02** [comment]
Concluído!
