### ISSUE TITLE
Deixar mais claro opção habilitar página de login de faturas

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/woocommerce-invoice-payment#68]
Está informação está confusa, se eu marcar o checkbox, ela ativa ou desativa a verificação de e-mail?

Seria interessante arrumar o texto para algo menos confuso.

![enable-disable](https://github.com/LinkNacional/woocommerce-invoice-payment/assets/74307223/c98d1721-ee5b-4f35-85e7-ae5533a8ef66)

**Comment by helonfranca02** [comment]
Concluído!

**Comment by emanuellopess** [comment]
Modificar texto

"Ativar a verificação de e-mail na fatura. _Esta funcionalidade irá ativar uma caixa de entrada de texto para o usuário informar o endereço de e-mail antes de exibir a fatura._"
